services:
  backend:
    build:
      context: ./src/api
      dockerfile: Dockerfile
    container_name: cipherdrop-backend
    ports:
      - "8000:8000"
    env_file:
      - src/api/.env
    environment:
      - NODE_ENV=production
      - FORCE_COLOR=1
    restart: unless-stopped
    depends_on:
      - redis
      - db

  frontend:
    build:
      context: ./src/web
      dockerfile: Dockerfile
    container_name: cipherdrop-frontend
    ports:
      - "8001:80"
    restart: unless-stopped
    depends_on:
      - backend

  redis:
    image: redis:7
    container_name: cipherdrop-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: [ "redis-server", "--appendonly", "yes" ]
    restart: unless-stopped
  db:
    image: postgres:15
    container_name: cipherdrop-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=cipherdrop
      - POSTGRES_PASSWORD=securepassword
      - POSTGRES_DB=cipherdropdb
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: unless-stopped
volumes:
    redis-data:
    db-data:
